### ISSUE TITLE
Create Progress Tracking Page

### ISSUE THREAD

**Issue by mfunkel** [darenc9/FitFuture#36]
**User Story**
As a user, I would like to view information about my fitness progress.

**Description**
The Progress Tracking Page involves designing and implementing the user interface for displaying a collection of [calculated statistics](https://github.com/darenc9/FitFuture/issues/32), trends, and graphs relating to their fitness progression.  This includes creating a dedicated page where users can view personalized metrics such as weight gained/lost.

**Acceptance Criteria**

- [x] gather and process data required for calculating progress
- [x] display calculated progression statistics
- [ ] filtering based on time (months / years) and desired statistic
- [x] capability to navigate to other parts of the workout app
- [x] responsive design to ensure cross device compatibility

**Testing**

- [x] verify progress page is accessible through the nav bar
- [ ] test display of accurate information
- [x] test responsiveness across devices
